Feat/msdk 339 get pending instructions refactor
PolymathNetwork/polymesh-sdk pull request #269
Opened 2020-11-19 16:03 UTC by shuffledex

2020-11-20 23:40 UTC, monitz87 requested changes

2020-11-20 23:40 UTC, monitz87 commented on src/api/entities/CurrentIdentity.ts
> +    const getPortfolios = await portfolios.getPortfolios();
ownedPortfolios

2020-11-20 23:40 UTC, monitz87 commented on src/api/entities/CurrentIdentity.ts
> +      }),
```suggestion
      P.filter(getPortfolios, portfolio => portfolio.isCustodiedBy(did)),
```

2020-11-20 23:40 UTC, monitz87 commented on src/api/entities/CurrentIdentity.ts
>      ];
You can just do `const portfolioIds = await P.map(allPortfolios, portfolio =>  portfolioLikeToPortfolioId(portfolio, context))`

2020-11-20 23:40 UTC, monitz87 commented on src/api/entities/__tests__/CurrentIdentity.ts
> +import { DefaultPortfolio } from '~/api/entities/DefaultPortfolio';
This should be part of the above import

2020-11-20 23:40 UTC, monitz87 commented on src/api/entities/__tests__/CurrentIdentity.ts
> +);
Are you sure these are necessary?

2020-11-23 19:15 UTC, shuffledex commented on src/api/entities/__tests__/CurrentIdentity.ts
> +);
yes, they are (portfolioCustodian)

2020-11-26 01:09 UTC, monitz87 approved these changes

2020-11-26 01:09 UTC, merged

2020-11-26 01:19 UTC, monitz87 commented
:tada: This PR is included in version 2.0.0-alpha.51 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/2.0.0-alpha.51)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v2.0.0-alpha.51)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-11-26 23:59 UTC, monitz87 commented
:tada: This PR is included in version 2.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/2.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v2.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-12-01 13:30 UTC, monitz87 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/2.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: