chore: remove PIA argument in compilance canTransfer rpc
PolymathNetwork/polymesh-sdk pull request #275
Opened 2020-11-27 15:25 UTC by shuffledex

2020-11-29 22:58 UTC, monitz87 requested changes

2020-11-29 22:58 UTC, monitz87 commented on src/api/entities/SecurityToken/Compliance/Requirements.ts
>      const { from = await this.context.getCurrentIdentity(), to } = args;
```suggestion
    const { from = await context.getCurrentIdentity(), to } = args;
```

2020-12-01 12:17 UTC, VictorVicente approved these changes

2020-12-01 12:17 UTC, merged

2020-12-02 12:35 UTC, monitz87 commented
:tada: This PR is included in version 2.0.0-alpha.54 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/2.0.0-alpha.54)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v2.0.0-alpha.54)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-12-16 17:01 UTC, monitz87 commented
:tada: This PR is included in version 3.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/3.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v3.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-12-17 15:41 UTC, monitz87 commented
:tada: This PR is included in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/3.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: