Feat/msdk 510 checkpoint all balances
PolymathNetwork/polymesh-sdk pull request #396
Opened 2021-03-18 16:28 UTC by shuffledex

2021-03-22 18:45 UTC, monitz87 requested changes

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +import { CheckpointId } from '~/polkadot';
Should be imported from `polymesh-types/types`

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +    const identityBalancesOf: { did: string; balance: BigNumber }[] = [];
currentDidBalances

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +    const balanceOf: { identity: Identity; balance: BigNumber }[] = [];
currentIdentityBalances

Also the type here can be `IdentityBalance[]`

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +      identityId: string;
did

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +      param: [(Ticker | CheckpointId)[], IdentityId];
params

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +    const balanceMulti: {
checkpointBalanceMultiParams

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +      const { did: identityId, balance } = identityBalancesOf[index];
Unnecessary rename

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +        }),
```suggestion
        ...balanceMulti.map(({ identityId: did }, index) => ({
            identity: new Identity({ did }, context),
            balance: balanceToBigNumber(rawBalanceMulti[index]),
          })),
```

2021-03-22 18:45 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +    const rawBalanceMulti = await query.checkpoint.balance.multi<Balance>(
checkpointBalances

2021-03-22 22:34 UTC, VictorVicente commented on src/api/entities/Checkpoint.ts
> +      checkpoint.balance.size([rawTicker, rawU64], rawIdentityId),
I thought the same thing but it doesn't work. `isEmpty` returns true if balance is 0, no matters if the value exists or not. 
I have tested it and I checked this behavior.
`size` is what PolkadotJS recommends to solve these cases.

2021-03-23 02:10 UTC, monitz87 commented on src/api/entities/Checkpoint.ts
> +      checkpoint.balance.size([rawTicker, rawU64], rawIdentityId),
My bad. `isEmpty` should work when 0 isn't a reasonable value

2021-03-28 21:20 UTC, monitz87 approved these changes

2021-03-28 21:20 UTC, merged

2021-03-28 21:34 UTC, monitz87 commented
:tada: This PR is included in version 5.0.0-beta.18 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/5.0.0-beta.18)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v5.0.0-beta.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-03-29 16:07 UTC, monitz87 commented
:tada: This PR is included in version 5.0.0-alpha.14 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/5.0.0-alpha.14)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v5.0.0-alpha.14)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-05-06 13:52 UTC, monitz87 commented
:tada: This PR is included in version 5.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/5.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v5.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: