feat(types): upgrade types according to Polymesh 3.0.1
PolymathNetwork/polymesh-sdk pull request #417
Opened 2021-04-07 15:07 UTC by VictorVicente

2021-04-13 19:26 UTC, monitz87 requested changes

2021-04-13 19:26 UTC, monitz87 commented on src/utils/conversion.ts
> +      value = tuple(stringToCddId(claim.cddId, context));
Why a tuple?

2021-04-13 21:08 UTC, VictorVicente commented on src/utils/conversion.ts
> +      value = tuple(stringToCddId(claim.cddId, context));
It shouldn't be a tuple

2021-04-13 21:31 UTC, monitz87 approved these changes

2021-04-13 21:34 UTC, merged

2021-04-13 21:48 UTC, monitz87 commented
:tada: This PR is included in version 5.0.0-alpha.18 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/5.0.0-alpha.18)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v5.0.0-alpha.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-04-14 12:59 UTC, monitz87 commented
:tada: This PR is included in version 5.0.0-beta.35 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/5.0.0-beta.35)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v5.0.0-beta.35)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-05-06 13:51 UTC, monitz87 commented
:tada: This PR is included in version 5.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/5.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v5.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: