feat: improve DD and CD creation parameters
PolymathNetwork/polymesh-sdk pull request #474
Opened 2021-06-08 16:22 UTC by shuffledex

2021-06-10 16:43 UTC, monitz87 requested changes

2021-06-10 16:43 UTC, monitz87 commented on src/api/procedures/configureDividendDistribution.ts
> +  const rawPortfolioNumber =
Use optionize here

2021-06-10 16:43 UTC, monitz87 commented on src/api/procedures/initiateCorporateAction.ts
> +    : null;
You can use `taxWithholdings && taxWithholdings.map(...);` instead of the ternary here

2021-06-14 12:29 UTC, VictorVicente approved these changes

2021-06-14 12:48 UTC, merged

2021-06-14 12:58 UTC, monitz87 commented
:tada: This PR is included in version 6.0.0-beta.11 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/6.0.0-beta.11)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v6.0.0-beta.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-06-15 15:10 UTC, monitz87 commented
:tada: This PR is included in version 6.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/6.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v6.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: