feat: sort tickers
PolymathNetwork/polymesh-sdk pull request #475
Opened 2021-06-09 13:25 UTC by shuffledex

2021-06-10 14:01 UTC, VictorVicente requested changes
There should be a test checking we're sorting them

2021-06-10 16:44 UTC, monitz87 reviewed
LGTM

2021-06-14 12:24 UTC, VictorVicente approved these changes

2021-06-14 12:24 UTC, merged

2021-06-14 12:34 UTC, monitz87 commented
:tada: This PR is included in version 6.0.0-beta.10 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/6.0.0-beta.10)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v6.0.0-beta.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-06-15 15:10 UTC, monitz87 commented
:tada: This PR is included in version 6.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/6.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v6.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: