feat(wip): adapt permissions to the new format
PolymathNetwork/polymesh-sdk pull request #479
Opened 2021-06-14 04:42 UTC by monitz87

2021-06-15 14:28 UTC, VictorVicente requested changes

2021-06-15 14:28 UTC, VictorVicente commented on src/utils/conversion.ts
> +export function txTagsToTxGroups(permissions: TransactionPermissions): TxGroup[] {
Should we change the name to  `transactionPermissionsToTxGroups`?

2021-06-22 15:32 UTC, shuffledex commented on src/utils/conversion.ts
> +          if (pallet) {
`pallet` never will defined at this point because the only way to accomplish that is removing the sort()

2021-07-07 19:47 UTC, monitz87 commented on src/utils/conversion.ts
> +    const tickers = tokenValues.map(({ ticker }) => stringToTicker(ticker, context));
Why was this change necessary?

2021-07-08 12:35 UTC, VictorVicente approved these changes

2021-07-08 18:22 UTC, merged

2021-07-08 18:32 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0-alpha.2 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0-alpha.2)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-08-05 15:07 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: