chore: increment coverage
PolymathNetwork/polymesh-sdk pull request #483
Opened 2021-06-22 02:59 UTC by shuffledex

2021-06-22 19:00 UTC, monitz87 requested changes

2021-06-23 14:36 UTC, shuffledex commented on src/utils/__tests__/conversion.ts
> +        exceptions: [TxTags.identity.AddClaim],
sounds I made this case to cover a line. If I add
`values: [ModuleName.Identity],`
the result is:
`"transactions":{"type":"Exclude","values":[],"exceptions":["identity.addClaim"]}`
and the test fails

2021-06-23 14:41 UTC, shuffledex commented on src/utils/conversion.ts
> +          const upperTag = stringUpperFirst(tag);
`extrinsicDict[palletName]`
palletName comes from splitTag that converts dispatchableName in upper case.
If a ModuleName is the first element of the array, the key must be in upper case as well to maintain compatibility

2021-06-24 06:12 UTC, monitz87 commented on src/utils/conversion.ts
> +          const upperTag = stringUpperFirst(tag);
TxTag dispatchable names are in lowercase

2021-06-29 18:20 UTC, monitz87 requested changes

2021-06-29 18:42 UTC, shuffledex commented on src/utils/conversion.ts
> +      values: uniq(txValues),
if Except has more than one tx from the same module name, I avoid the duplicates

2021-06-29 18:44 UTC, monitz87 commented on src/utils/conversion.ts
> +      values: uniq(txValues),
You're only adding the module name once per pallet to `txValues`

2021-06-30 12:37 UTC, shuffledex commented on src/utils/conversion.ts
> +      values: uniq(txValues),
done

2021-07-01 04:42 UTC, monitz87 approved these changes

2021-07-01 04:42 UTC, merged

2021-07-08 18:32 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0-alpha.2 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0-alpha.2)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-08-03 15:19 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-08-05 15:07 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: