feat: refactor PIA and CAA remove procedures
PolymathNetwork/polymesh-sdk pull request #493
Opened 2021-06-29 18:39 UTC by shuffledex

2021-07-05 19:05 UTC, monitz87 requested changes
There are linting errors

2021-07-05 19:05 UTC, monitz87 commented on src/api/procedures/removeCorporateActionsAgent.ts
> +        'We can not perform this procedure with more than one Corporate Actions Agent involved',
"There must be one (and only one) Corporate Actions Agent assigned to this Security Token"

2021-07-05 19:05 UTC, monitz87 commented on src/api/procedures/removePrimaryIssuanceAgent.ts
> +        'We can not perform this procedure with more than one Primary Issuance Agent involved',
"There must be one (and only one) Primary Issuance Agent assigned to this Security Token"

2021-07-05 19:06 UTC, monitz87 commented
There are 5 code smells as well

2021-07-06 11:28 UTC, shuffledex commented
> There are 5 code smells as well

I have to disable the `deprecated` warnings

2021-07-06 17:45 UTC, monitz87 approved these changes

2021-07-06 17:49 UTC, merged

2021-07-08 18:32 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0-alpha.2 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0-alpha.2)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-08-03 15:19 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-08-05 15:07 UTC, monitz87 commented
:tada: This PR is included in version 7.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/7.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v7.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: