feat: agentOf method
PolymathNetwork/polymesh-sdk pull request #543
Opened 2021-08-18 21:45 UTC by shuffledex

2021-08-18 23:51 UTC, monitz87 requested changes

2021-08-18 23:51 UTC, monitz87 commented on src/types/index.ts
> +export interface AssetPermission {
TokenWithGroup

2021-08-18 23:51 UTC, monitz87 commented on src/api/entities/Identity/index.ts
> +   * Retrieve all assets with given permissions where this Identity is an Agent
Retrieve all the Security Tokens for which this Identity is an Agent, with the corresponding permission group

2021-08-18 23:51 UTC, monitz87 commented on src/api/entities/Identity/__tests__/index.ts
> +              // TODO replace by entityMockUtils.getAgentInstance once it is merge
Why not base this branch off the other?

2021-08-18 23:51 UTC, monitz87 commented on src/types/index.ts
> +  permissions: GroupPermissions;
I would have this just be `group: KnownPermissionGroup | CustomPermissionGroup`

2021-08-18 23:51 UTC, monitz87 commented on src/api/entities/Identity/index.ts
> +    const rawAgentOf = await externalAgents.agentOf.entries(rawDid);
tokenEntries

2021-08-18 23:51 UTC, monitz87 commented on src/api/entities/Identity/index.ts
> +      };
const ticker = tickerToString(key.args[1]);
      const agent = new Agent({ did, ticker }, context);
      const token = new SecurityToken({ ticker }, context);
      const group = await agent.getPermissionGroup();

      return {
        token,
        group,
      };

2021-08-23 22:05 UTC, monitz87 commented
Missing coverage

2021-08-23 22:13 UTC, monitz87 requested changes

2021-08-23 22:13 UTC, monitz87 commented on src/api/entities/Identity/__tests__/index.ts
>                agent: identity as Agent,
You didn't replace it

2021-08-23 22:13 UTC, monitz87 commented on src/api/entities/Identity/index.ts
> +  public async agentOf(): Promise<TokenWithGroup[]> {
I think `getTokenPermissions` might be a better fit

2021-08-23 22:13 UTC, monitz87 commented on src/api/entities/Identity/index.ts
> +      const group = await agentWithGroup!.group;
Can't you do

```
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
const { group } = agents.find(({ agent }) => agent.did === did)!;
```

2021-08-24 22:35 UTC, monitz87 requested changes

2021-08-24 22:35 UTC, monitz87 commented on src/api/entities/Identity/__tests__/index.ts
>                agent: identity as Agent,
Why did you mark this as resolved?

2021-08-25 11:18 UTC, shuffledex commented on src/api/entities/Identity/__tests__/index.ts
>                agent: identity as Agent,
'cos I don't see it anymore

2021-08-25 11:20 UTC, shuffledex commented on src/api/entities/Identity/__tests__/index.ts
>                agent: identity as Agent,
the new code is

```
      entityMockUtils.configureMocks({
        securityTokenOptions: {
          ticker,
        },
        agentOptions: {
          getPermissionGroup: group,
        },
      });
```

2021-08-25 13:35 UTC, monitz87 commented on src/api/entities/Identity/__tests__/index.ts
>                agent: identity as Agent,
All good then

2021-08-25 13:36 UTC, monitz87 approved these changes

2021-08-25 13:55 UTC, merged

2021-08-25 14:06 UTC, monitz87 commented
:tada: This PR is included in version 8.0.0-beta.6 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/8.0.0-beta.6)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v8.0.0-beta.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-09-10 17:28 UTC, monitz87 commented
:tada: This PR is included in version 9.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/9.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v9.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: