Feat/msdk 594 abdicate
PolymathNetwork/polymesh-sdk pull request #545
Opened 2021-08-24 16:37 UTC by shuffledex

2021-08-30 18:53 UTC, monitz87 requested changes

2021-08-30 18:53 UTC, monitz87 commented on src/api/procedures/__tests__/waivePermissions.ts
> +  test('should throw an error if the Identity is not part of the Agent Group', async () => {
is not an Agent for the Security Token

2021-08-30 18:53 UTC, monitz87 commented on src/api/procedures/__tests__/waivePermissions.ts
> +  test('should add a abdicate transaction to the queue', async () => {
```suggestion
  test('should add an abdicate transaction to the queue', async () => {
```

2021-08-30 19:33 UTC, shuffledex commented on src/api/procedures/waivePermissions.ts
> +};
my mistake

2021-08-31 03:14 UTC, monitz87 requested changes

2021-08-31 03:14 UTC, monitz87 commented on src/api/procedures/__tests__/waivePermissions.ts
> +  test('should throw an error if the Identity is not is not an Agent for the Security Token', async () => {
```suggestion
  test('should throw an error if the Identity is not an Agent for the Security Token', async () => {
```

2021-09-02 22:09 UTC, monitz87 approved these changes

2021-09-02 22:09 UTC, monitz87 requested changes
We still have to figure out the permissions issue

2021-09-03 13:14 UTC, monitz87 approved these changes

2021-09-03 13:15 UTC, merged

2021-09-03 13:26 UTC, monitz87 commented
:tada: This PR is included in version 9.0.0-beta.4 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/9.0.0-beta.4)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v9.0.0-beta.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-09-10 17:27 UTC, monitz87 commented
:tada: This PR is included in version 9.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/9.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v9.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: