Feat/msdk 571 history of agents
PolymathNetwork/polymesh-sdk pull request #564
Opened 2021-09-13 16:59 UTC by shuffledex

2021-09-14 21:30 UTC, monitz87 requested changes

2021-09-14 21:30 UTC, monitz87 commented on src/api/entities/SecurityToken/index.ts
> +   * Retrieve all Agent Operation History
```suggestion
   * Retrieve this Security Token's Operation History
   *
   * @note Operations are grouped by the Agent Identity who performed them
```

2021-09-14 21:30 UTC, monitz87 commented on src/api/entities/__tests__/Account.ts
>              address: address,
```suggestion
            address,
```

2021-09-14 21:30 UTC, monitz87 commented on src/middleware/queries.ts
> + * Get the history of each external agent in ticker
```suggestion
 * Get the transaction history of each external agent of a token
```

2021-09-14 21:30 UTC, monitz87 commented on src/types/index.ts
> +export interface HistoricAgentOperation {
```suggestion
/**
 * Events triggered by transactions performed by an Agent Identity, related to the Token's configuration
 *   For example: changing compliance requirements, inviting/removing agent Identities, freezing/unfreezing transfers
 *
 * Token transfers (settlements or movements between Portfolios) do not count as Operations
 */
export interface HistoricAgentOperation {
```

2021-09-14 21:30 UTC, monitz87 commented on src/types/index.ts
> +  identity: Identity;
```suggestion
  /**
   * Agent Identity that performed the operations
   */
  identity: Identity;
```

2021-09-14 21:30 UTC, monitz87 commented on src/types/index.ts
> +  history: EventIdentifier[];
```suggestion
  /**
   * list of Token Operation Events that were triggered by the Agent Identity
   */
  history: EventIdentifier[];
```

2021-09-15 20:00 UTC, monitz87 requested changes

2021-09-15 20:36 UTC, shuffledex commented on src/api/entities/SecurityToken/index.ts
> +  public async getOperationHistory(): Promise<HistoricAgentOperation[]> {
No. The middleware endpoint can't be paginated as it does stream processing.

2021-09-20 19:22 UTC, monitz87 approved these changes

2021-09-21 02:48 UTC, merged

2021-09-21 03:01 UTC, monitz87 commented
:tada: This PR is included in version 10.0.0-beta.4 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/10.0.0-beta.4)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v10.0.0-beta.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-09-21 03:15 UTC, monitz87 commented
:tada: This PR is included in version 10.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/10.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v10.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: