fix: 🐛 MSDK-748 Handle CAId conversion in LinkCADocs
PolymathNetwork/polymesh-sdk pull request #608
Opened 2021-11-30 12:57 UTC by prashantasdeveloper

### JIRA Link

https://polymath.atlassian.net/browse/MSDK-748

2021-11-30 16:53 UTC, monitz87 requested changes

2021-11-30 16:53 UTC, monitz87 commented on src/api/procedures/linkCaDocs.ts
>    // eslint-disable-next-line @typescript-eslint/naming-convention
This can be deleted

2021-11-30 17:29 UTC, prashantasdeveloper commented on src/api/procedures/linkCaDocs.ts
>    // eslint-disable-next-line @typescript-eslint/naming-convention
It was needed for `rawCAId`

```
74:9  error  Variable name `rawCAId` must match one of the following formats: strictCamelCase, UPPER_CASE  @typescript-eslint/naming-convention
```

2021-12-01 19:37 UTC, monitz87 requested changes

2021-12-01 19:37 UTC, monitz87 commented on src/api/procedures/linkCaDocs.ts
>    // eslint-disable-next-line @typescript-eslint/naming-convention
Change the name to `rawCaId`

2021-12-06 15:07 UTC, monitz87 approved these changes

2021-12-06 15:45 UTC, polymath-eric approved these changes

2021-12-06 20:21 UTC, merged

2021-12-06 20:33 UTC, monitz87 commented
:tada: This PR is included in version 11.0.0-beta.6 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/11.0.0-beta.6)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v11.0.0-beta.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-10 17:56 UTC, monitz87 commented
:tada: This PR is included in version 12.0.0-alpha.7 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/12.0.0-alpha.7)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v12.0.0-alpha.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-10 19:13 UTC, monitz87 commented
:tada: This PR is included in version 11.0.0-limbo.1 :tada:

The release is available on:
- [npm package (@limbo dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/11.0.0-limbo.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v11.0.0-limbo.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-13 14:07 UTC, monitz87 commented
:tada: This PR is included in version 12.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/12.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v12.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-14 19:40 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-14 21:16 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-alpha.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-03 11:39 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: