Msdk 743 update to 1.1 types
PolymathNetwork/polymesh-sdk pull request #616
Opened 2021-12-06 22:40 UTC by polymath-eric

2021-12-07 12:29 UTC, VictorVicente requested changes
Hey @polymath-eric, well done.
I think you need to fix the test case for the versioning control. That's the reason why all tests are failing.

2021-12-07 12:29 UTC, VictorVicente commented on src/polkadot/definitions.ts
> -
This file must be ignored, please restore this line

2021-12-07 18:26 UTC, monitz87 approved these changes

2021-12-07 22:02 UTC, VictorVicente approved these changes

2021-12-07 22:02 UTC, merged

2021-12-09 20:29 UTC, monitz87 commented
:tada: This PR is included in version 11.0.0-beta.7 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/11.0.0-beta.7)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v11.0.0-beta.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-10 17:56 UTC, monitz87 commented
:tada: This PR is included in version 12.0.0-alpha.7 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/12.0.0-alpha.7)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v12.0.0-alpha.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-10 19:13 UTC, monitz87 commented
:tada: This PR is included in version 11.0.0-limbo.1 :tada:

The release is available on:
- [npm package (@limbo dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/11.0.0-limbo.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v11.0.0-limbo.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-13 14:07 UTC, monitz87 commented
:tada: This PR is included in version 12.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/12.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v12.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-14 19:40 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-14 21:16 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-alpha.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-03 11:39 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: