Msdk 779 network namespace
PolymathNetwork/polymesh-sdk pull request #654
Opened 2022-01-04 19:40 UTC by polymath-eric

Creates a network namespace that contains all previous middleware
methods as well as some from root

- sdk.getLastestBlock -> sdk.network.getLatestBlock
- sdk.getNetworkVersion -> sdk.network.getVersion
- sdk.getNetworkProperties -> sdk.network.getProperties
- sdk.getTransactionFees -> sdk.network.getTransactionFees
- sdk.getTreasuryAccount -> sdk.network.getTreasuryAccount
- sdk.getTreasuryBalance -> sdk.network.getTreasuryBalance
- sdk.transferPolyx -> sdk.network.transferPolyx
- sdk.middleware.getEventByIndexedArgs -> sdk.network.getEventByIndexedArgs
- sdk.middleware.getEventsByIndexedArgs -> sdk.network.getEventsByIndexedArgs
- sdk.middleware.getTransactionByHash -> sdk.network.getTransactionByHash

BREAKING CHANGE: 🧨 Moved methods

2022-01-06 12:47 UTC, prashantasdeveloper commented
LGTM

2022-01-06 17:05 UTC, polymath-eric commented
@monitz87 Prashant gave an approval for this one.

2022-01-07 13:46 UTC, prashantasdeveloper approved these changes

2022-01-10 19:15 UTC, monitz87 requested changes

2022-01-10 19:15 UTC, monitz87 commented on src/Network.ts
> +  public getTransactionFees(args: { tag: TxTag }): Promise<BigNumber> {
I think we should go ahead and change this (and the underlying context method) to `getProtocolFees`. When fetching fees for a `PolymeshTransaction`, they are broken down between `gas` and `protocol`, so we'd be more consistent

2022-01-12 21:14 UTC, monitz87 approved these changes

2022-01-12 21:43 UTC, merged

2022-01-12 21:58 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-alpha.14 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-alpha.14)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-alpha.14)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-04 17:51 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-alpha.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-20 18:18 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-25 15:57 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: