Msdk 787 rename security token
PolymathNetwork/polymesh-sdk pull request #664
Opened 2022-01-10 15:44 UTC by polymath-eric

Renames SecurityToken to Asset and updates references to token to asset.

The term security token was a carry over from Ethereum, however the term Asset is more descriptive. 
Since this is a core domain concept this introduces quite a number of breaking changes.

Essentially any reference to SecurityToken is replaced with Asset, and any reference to token is 
replaced with asset

Methods
- sdk.assets.createToken -> sdk.assets.createAsset
- sdk.assets.getSecurityTokens -> sdk.assets.getAssets
- sdk.assets.getSecurityToken -> sdk.assets.getAsset

Identity#
- getTokenBalance -> getAssetBalances
- getTrustingTokens -> getTrustingAssets
- getHeldTokens -> getHeldAssets
- getScopeId (args: token -> asset)
- getTokenBalance -> getAssetBalance
- getHeldTokens -> getHeldAssets
- getDividendDistributionsForAssets (args: token -> asset
- getPendingDistributions (args: tokens -> assets)

Account#
- checkPermissions (args: tokens -> assets)
- hasPermissions (args: tokens -> assets)

AuthorizationRequest
- (type) AuthorizationType.JoinIdentity (args: tokens -> assets)

Portfolio#
- getTokenBalances -> getAssetBalances. (args: token -> asset, return: token -> asset)

TickerReservation#
- createToken -> createAsset

Enums
- TickerReservationStatus.TokenCreated -> TickerReservationStatus.AssetCreated
- TokenType -> AssetType
- TokenIdentifierType -> SecurityIdentifierType
- KnownTokenType -> KnownSecurityType
- TokenIdentifierType -> SecurityIdentifierType
- TokenIdentifier -> SecurityIdentifier
- TokenDocument -> AssetDocument
- TokenManagement -> AssetManagement
- AdvancedTokenManagement -> AdvancedAssetManagement
- TokenWithGroup -> AssetWithGroup

Properties
- Checkpoint.token -> Checkpoint.asset
- CheckpointSchedule.token -> CheckpointSchedule.asset
- CorporateActionBase.token -> CorporateActionBase.asset (inherited by CorporateAction, DividendDistribution)
- PermissionGroup.token -> PermissionGroup.asset (inherited by KnownPermissionGroup, CustomPermissionGroup)
- DefaultTrustedClaimIssuer.token -> DefaultTrustedClaimIssuer.asset
- Leg.token -> Leg.asset
- Sto.token -> Offering.asset

Classes
- TokenPermissions -> AssetPermissions
- TokenHolders -> AssetHolders
- TokenDocument -> AssetDocument
- STO -> Offering

Arguments
- CreateSecurityTokenParams -> CreateAssetParams. 
    (inherited by CreateAssetWithTickerParams) 
    (args: tokenType -> assetType,  tokenIdentifiers -> securityIdentifiers )

Asset permissions
- checkPermissions (args: token -> asset)
- hasPermissions (args: token -> asset)
- getGroup (args: token -> asset)
- enabledAt (args: token -> asset)
- getOperationHistory (args: token -> asset)

Type Guards
- isSecurityToken -> isAsset

File Imports
- File paths had SecurityToken replaced with Asset

2022-01-11 21:58 UTC, polymath-eric commented
SonarCloud is red, but its from "deprecated" methods being moved.

I think these should be ignored since they are mainly in tests, and we aren't trying to introduce changes beyond the rename here.

2022-01-18 15:28 UTC, prashantasdeveloper reviewed
Some nits. Other than than LGTM

2022-01-18 16:30 UTC, polymath-eric commented on src/api/entities/Asset/index.ts
> +   * Retrieve the Asset's asset identifiers list
What do you mean here?

I noticed I can remove the "asset" on this line.

2022-01-18 17:43 UTC, prashantasdeveloper commented on src/api/entities/Asset/index.ts
> +   * Retrieve the Asset's asset identifiers list
Yes, you can remove the extra "asset"

2022-01-19 13:26 UTC, prashantasdeveloper reviewed
Overall LGTM, you just left some commented out code

2022-01-19 13:26 UTC, prashantasdeveloper commented on src/api/procedures/__tests__/issueAsset.ts
> +      // } as IssueAssetParams;
These got left out

2022-01-28 02:24 UTC, monitz87 requested changes

2022-01-28 02:24 UTC, monitz87 commented on src/internal.ts
>  // export { createProposal, CreateProposalParams } from '~/api/procedures/createProposal';
Remove this

2022-01-28 02:24 UTC, monitz87 commented on src/internal.ts
>  // export { editProposal, EditProposalParams } from '~/api/procedures/editProposal';
And this

2022-01-28 02:24 UTC, monitz87 commented on src/internal.ts
>  // export { voteOnProposal, VoteOnProposalParams } from '~/api/procedures/voteOnProposal';
And this

2022-01-28 02:24 UTC, monitz87 commented on src/middleware/types.ts
> -export type QueryTokensHeldByDidArgs = {
These types are autogenerated, so we shouldn't mess with them

2022-01-28 02:24 UTC, monitz87 commented on src/middleware/queries.ts
> +export function assetsByTrustedClaimIssuer(
I think this function (and the other one) should retain their original names, since they are named after their underlying GQL query

2022-01-28 02:24 UTC, monitz87 commented on src/middleware/queries.ts
> + * Get the transaction history of each external agent of a asset
```suggestion
 * Get the transaction history of each external agent of an Asset
```

2022-01-28 02:24 UTC, monitz87 commented on src/polkadot/augment-api-errors.ts
> +       * No such asset.
Autogenerated

2022-01-28 02:24 UTC, monitz87 commented on src/polkadot/augment-api-tx.ts
> +       * Initializes a new token, with the initiating account as its owner.
Autogenerated

2022-01-28 02:24 UTC, monitz87 commented on src/testUtils/mocks/dataSources.ts
> +  return createMockCodec({ ...st }, !asset) as SecurityToken;
This should stay the same (reflects the mesh type)

2022-01-28 02:24 UTC, monitz87 commented on src/testUtils/mocks/entities.ts
> +  // Proposal,
Remove this

2022-01-28 02:24 UTC, monitz87 commented on src/testUtils/mocks/entities.ts
>  import { ProposalDetails, ProposalStage /*, ProposalState */ } from '~/api/entities/Proposal/types';
Remove the comment

2022-01-28 02:24 UTC, monitz87 commented on src/types/index.ts
> +  /*, Proposal */
Remove this

2022-01-28 02:24 UTC, monitz87 commented on src/types/index.ts
> +export enum KnownSecurityType {
I think this should be `KnownAssetType`

2022-01-28 02:24 UTC, monitz87 commented on src/types/index.ts
>   *   all permissions of that type (i.e. if `tokens` is null, the key has permissions over all
```suggestion
 *   all permissions of that type (i.e. if `assets` is null, the key has permissions over all
```

2022-01-28 02:24 UTC, monitz87 commented on src/types/index.ts
> + * This represents all Permission Groups of a specific Asset, separated by `known` and `custom`
```suggestion
 * All Permission Groups of a specific Asset, separated by `known` and `custom`
```

2022-01-28 02:24 UTC, monitz87 commented on src/types/index.ts
> +   * list of required Assets permissions
```suggestion
   * list of required Asset permissions
```

2022-01-28 02:24 UTC, monitz87 commented on src/types/internal.ts
> +export type InternalSecurityType = KnownSecurityType | { Custom: CustomAssetTypeId };
InternalAssetType

2022-01-28 02:24 UTC, monitz87 commented on src/utils/conversion.ts
> +export function internalSecurityTypeToAssetType(
Rename this to match the types

2022-01-28 02:24 UTC, monitz87 commented on src/utils/conversion.ts
>    // eslint-disable-next-line @typescript-eslint/naming-convention
This can be safely removed

2022-01-28 21:40 UTC, polymath-eric commented on src/api/entities/Asset/TransferRestrictions/Count.ts
> +import { TransferRestrictionBase } from '~/api/entities/Asset/TransferRestrictions/TransferRestrictionBase';
I tried and it causes the tests to spew

```
TypeError: Class extends value undefined is not a constructor or null

      15 |  * Handles all Count Transfer Restriction related functionality
      16 |  */
    > 17 | export class Count extends TransferRestrictionBase<TransferRestrictionType.Count> {
  ```
  
  although it does build alright.

2022-02-02 15:38 UTC, monitz87 commented on src/api/entities/Asset/TransferRestrictions/Count.ts
> +import { TransferRestrictionBase } from '~/api/entities/Asset/TransferRestrictions/TransferRestrictionBase';
You have to move the import in `internal.ts` (order matters). It worked for me if I put it right after `export { Authorizations } from '~/api/entities/common/namespaces/Authorizations';`

2022-02-02 15:38 UTC, monitz87 commented on src/api/entities/Asset/TransferRestrictions/Percentage.ts
> +import { TransferRestrictionBase } from '~/api/entities/Asset/TransferRestrictions/TransferRestrictionBase';
Reminder

2022-02-02 20:00 UTC, polymath-eric commented on src/api/entities/Asset/TransferRestrictions/Count.ts
> +import { TransferRestrictionBase } from '~/api/entities/Asset/TransferRestrictions/TransferRestrictionBase';
That fixed it for me as well.

2022-02-02 22:45 UTC, monitz87 requested changes

2022-02-02 22:45 UTC, monitz87 commented on src/api/procedures/modifyOfferingTimes.ts
> +function validateInput(
Minor thing, but I'd move this so that the export is the last thing in the file

2022-02-02 22:45 UTC, monitz87 commented on src/internal.ts
> +  InvestInOfferingParams as InvestInStoParams,
Why keep these names here?

2022-02-02 22:45 UTC, monitz87 commented on src/internal.ts
> +  RedeemTokensParams as RedeemAssetParams,
Why the aliases?

2022-02-02 22:45 UTC, monitz87 commented on src/polkadot/augment-api-tx.ts
> +       * Initializes a new security, with the initiating account as its owner.
```suggestion
       * Initializes a new security token, with the initiating account as its owner.
```
That's the original comment

2022-02-02 22:45 UTC, monitz87 commented on src/api/entities/Offering/types.ts
> +   * All Assets tokens in the Offering have been sold
```suggestion
   * All Asset tokens in the Offering have been sold
```

2022-02-02 22:45 UTC, monitz87 commented on src/api/procedures/investInOffering.ts
> +   * amount of Assets tokens to purchase
```suggestion
   * amount of Asset tokens to purchase
```

2022-02-03 15:33 UTC, monitz87 approved these changes

2022-02-03 15:33 UTC, merged

2022-02-03 15:46 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-alpha.18 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-alpha.18)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-alpha.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-04 17:51 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-alpha.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-20 18:17 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: