feat: 🎸 Add `trustedFor` method in DefaultTrustedClaimIssuer
PolymathNetwork/polymesh-sdk pull request #675
Opened 2022-01-25 18:15 UTC by prashantasdeveloper

`trustedFor` has been converted from static property to a method which will now return the claim types which Claim Issuer is trusted.

BREAKING CHANGE: 🧨 `DefaultTrustedClaimIssuer.trustedFor` has been converted to an async method returning claim types for which Claim Issuer is trusted.

2022-01-25 19:10 UTC, polymath-eric approved these changes
LGTM, left a potential nit, but might be OK to leave.

Minor detail in the commit message, but technically "static property" means it's defined on the class itself and not instances. I know what you mean, but it's an overloaded word in the context.

2022-01-27 19:58 UTC, monitz87 requested changes
You forgot to list the changes to the `TrustedClaimIssuer` interface as breaking changes (and the methods that are affected by the interface change)

2022-01-27 19:58 UTC, monitz87 commented on src/api/procedures/modifyTokenTrustedClaimIssuers.ts
> +  }[];
This can be `InputTrustedClaimIssuer[]`

2022-01-31 10:16 UTC, prashantasdeveloper commented on src/api/entities/DefaultTrustedClaimIssuer.ts
> +        message: `The Identity with DID "${did}" is no longer a trusted issuer for "${ticker}"`,
As explained by Jere, I suppose no change is required here.

2022-02-02 18:15 UTC, polymath-eric approved these changes

2022-02-03 18:00 UTC, monitz87 approved these changes

2022-02-03 18:00 UTC, monitz87 commented on src/types/index.ts
> +   * an undefined value means that the issuer is trusted for all claim types.
```suggestion
   * a null value means that the issuer is trusted for all claim types
```

2022-02-03 20:15 UTC, merged

2022-02-03 20:28 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-alpha.21 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-alpha.21)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-alpha.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-04 17:51 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-alpha.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-20 18:17 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-25 15:57 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: