fix: 🐛 Allow `modifyClaims` to modify claim with cdd_id `0x00`
PolymathNetwork/polymesh-sdk pull request #677
Opened 2022-01-27 13:53 UTC by prashantasdeveloper

2022-01-28 13:45 UTC, polymath-eric approved these changes

2022-01-31 13:40 UTC, VictorVicente requested changes
@prashantasdeveloper I left a comment regarding CddIds.
Also, could you check we are covering all these cases with unit tests:
1) `currentCddId` is the default and `newCddId` is different (should success)
2) `newCddId` is the default and `currentCddId` is different (should success)
3) `currentCddId` is some_value and `newCddId` is the another_value (should be invalid)

2022-02-03 18:41 UTC, monitz87 approved these changes

2022-02-03 18:41 UTC, monitz87 commented on src/utils/constants.ts
> + * Default cdd_id associated with an Identity on chain
```suggestion
 * Default CDD ID associated with an Identity on chain. Used for Identities onboarded without PUIS
```

2022-02-04 15:25 UTC, VictorVicente approved these changes

2022-02-04 15:32 UTC, merged

2022-02-04 15:48 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-beta.5 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-beta.5)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-beta.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-03 11:39 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: