feat: 🎸 Add `Subsidy` entity with `quit` procedure
PolymathNetwork/polymesh-sdk pull request #681
Opened 2022-02-03 13:46 UTC by prashantasdeveloper

2022-02-03 15:46 UTC, monitz87 commented on src/api/entities/Subsidy/index.ts
> +  subsidizerAddress: string;
I think `beneficiary` and `subsidizer` are enough here. We can explain they're addresses with JSDoc comments ("beneficiary address", "subsidizer address")

2022-02-03 15:52 UTC, monitz87 commented on src/api/entities/Subsidy/index.ts
> +    return subsidy !== null && subsidy.subsidizer.address === subsidizerAddress;
You should be able to use `subsidy.subsidizer.isEqual(subsidizer)`

2022-02-03 16:11 UTC, monitz87 commented
You should modify `Context.accountSubsidy` and `Account.getSubsidy` to return

```
interface SubsidyWithAllowance {
  subsidy: Subsidy;
  allowance: BigNumber;
}
```

And also add `getAllowance(): Promise<BigNumber>` to the `Subsidy` entity

2022-02-07 18:22 UTC, monitz87 requested changes

2022-02-08 14:22 UTC, monitz87 commented on src/api/procedures/quitSubsidy.ts
> +  console.log(exists);
```suggestion
```

2022-02-08 14:50 UTC, polymath-eric approved these changes

2022-02-08 15:48 UTC, merged

2022-02-08 16:06 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-alpha.27 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-alpha.27)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-alpha.27)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-04 17:50 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-alpha.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-20 18:17 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: