refactor: 💡 Refactor procedures to support batched transactions
PolymathNetwork/polymesh-sdk pull request #689
Opened 2022-02-18 12:23 UTC by prashantasdeveloper

#### Changelog 

`modifyAsset`, `modifyVenue`, `setAssetDocuments`,
`addTransferRestriction` are modified to support batched transaction.

Confluence doc for reference - https://polymath.atlassian.net/wiki/spaces/PM/pages/2090795009/Multi-transaction+procedures

2022-02-28 21:01 UTC, monitz87 requested changes

2022-03-03 23:17 UTC, monitz87 requested changes
You forgot to delete `batchArguments`

2022-03-04 15:05 UTC, polymath-eric approved these changes

2022-03-04 20:04 UTC, monitz87 approved these changes

2022-03-07 10:10 UTC, merged

2022-03-07 10:29 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-alpha.2 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-alpha.2)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-20 18:16 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: