feat: 🎸 Throw Polymesh error when createType errors
PolymathNetwork/polymesh-sdk pull request #691
Opened 2022-02-22 15:26 UTC by polymath-eric

Returns a Polymesh error type to provide better context when the
createType fails for whatever reason

2022-02-24 13:40 UTC, prashantasdeveloper approved these changes
LGTM

2022-02-28 14:40 UTC, monitz87 requested changes

2022-03-01 14:08 UTC, monitz87 approved these changes

2022-03-01 18:08 UTC, monitz87 approved these changes

2022-03-01 18:09 UTC, merged

2022-03-01 18:26 UTC, monitz87 commented
:tada: This PR is included in version 13.0.0-alpha.29 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/13.0.0-alpha.29)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v13.0.0-alpha.29)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-04 17:50 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-alpha.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-20 18:16 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: