feat: 🎸 validate chain spec version when connecting
PolymathNetwork/polymesh-sdk pull request #752
Opened 2022-05-26 12:24 UTC by monitz87

### Description

- Fetch and compare chain spec version as well as rpc node version with the expected ranges, throw if not compatible

### Breaking Changes

- Throw an error instead of a warning when the chain versions aren't
within the expected ranges

### JIRA Link

https://polymath.atlassian.net/browse/DA-324

### Checklist

- [ ] Updated the Readme.md (if required) ?

2022-05-26 14:48 UTC, monitz87 commented on src/Polymesh.ts
> +    await assertExpectedChainVersion(nodeUrl);
The confluence doc says it should be an error for major version mismatches, which I think is the sensible choice

2022-05-26 14:49 UTC, monitz87 commented on src/utils/internal.ts
> +          .replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1.')
Still works, I tried it with spec version 50_000_000 for example

2022-05-26 15:39 UTC, VictorVicente requested changes

2022-05-30 12:42 UTC, VictorVicente approved these changes

2022-05-30 12:42 UTC, merged

2022-05-30 23:03 UTC, monitz87 commented
:tada: This PR is included in version 14.0.0-alpha.16 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/14.0.0-alpha.16)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v14.0.0-alpha.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-12 19:12 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0-beta.1)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v15.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-10 17:02 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v15.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: