Chore/adapt resolutions to package managers
PolymathNetwork/polymesh-sdk pull request #765
Opened 2022-06-02 13:26 UTC by monitz87

### Description

- Add support for npm and pnpm resolutions for consumers that don't use yarn

### Checklist

- [x] Updated the Readme.md (if required) ?

2022-06-02 14:07 UTC, VictorVicente approved these changes

2022-06-02 20:01 UTC, polymath-eric requested changes

2022-06-02 20:01 UTC, polymath-eric commented on package.json
> +    "@polkadot/api-augment": "8.0.2",
These should be 8.1.1 now.

I made a PR earlier that bumped the version since 8.0.2 had a bug in pagination calls.

2022-06-03 16:39 UTC, polymath-eric approved these changes

2022-06-03 16:39 UTC, merged

2022-06-03 16:57 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0-alpha.4 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymathnetwork/polymesh-sdk/v/15.0.0-alpha.4)
- [GitHub release](https://github.com/PolymathNetwork/polymesh-sdk/releases/tag/v15.0.0-alpha.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-10 17:01 UTC, monitz87 commented
:tada: This PR is included in version 15.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-sdk/v/15.0.0)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-sdk/releases/tag/v15.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: